#!/usr/bin/env bash
# installs and configures nginx to serve "Holberton School" at /

sudo apt update
sudo apt install -y nginx

echo "<html><p>Holberton School</p></html>" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
